import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import TanstackProvider from '@/providers/TanstackProvider';
// import ReduxProvider from '@/providers/ReduxProvider';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import AuthProvider from '@/providers/AuthProvider';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',  // Correct variable font weight range
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',  // Correct variable font weight range
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <ReduxProvider> */}
          <TanstackProvider>
            <AuthProvider>
              <ToastContainer />
              <div>
                {children}
              </div>
              <div className='p-10 block sm:hidden'>
                <h1 className='font-bold text-4xl'>
                  Opsie! 
                </h1>
                <span className='font-light text-md'>
                  This App Not Support on Your Device Screen
                </span>
              </div>
            </AuthProvider>
          </TanstackProvider>
        {/* </ReduxProvider> */}
      </body>
    </html>
  );
}
